---

apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  initContainers:
  - name: git-clone
    image: alpine
    command: ["sh", "-c"]
    args:
    - |
      apk add --no-cache git openssh
      mkdir ~/.ssh/
      cp .ssh-src/* ~/.ssh/
      eval `ssh-agent -s`
      ssh-add ~/.ssh/id_rsa
      ssh -v git@github.com
      git clone https://github.com/yilas/kaniko-demo.git /workspace
    volumeMounts:
    - name: docker-volume
      mountPath: /workspace

  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args:
    - "--context=dir:///workspace"
    - "--destination=strangebubble/devops-toolkit:1.0.0"
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: docker-volume
        mountPath: /workspace
  restartPolicy: Never

  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: docker-volume
      emptyDir: {}
